import type { Metadata } from "next";
import "./css/globals.css";
import Header from "./header";
import Footer from "./footer";

export const metadata: Metadata = {
  title: "BOMZ",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="kr">
      <head>
        <link href="https://hangeul.pstatic.net/hangeul_static/css/nanum-square-round.css" rel="stylesheet"></link>
      </head>
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
