import type { Metadata } from "next";
import "./globals.css";
import Header from "./header";
import Footer from "./footer";


export const metadata: Metadata = {
  title: "BOMZ",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="kr">
      <body>
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
